version: '3'

services:
  frontend:
    build: './alpha_blog_front_end'
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: './Node_Authentication'
    ports:
      - "8000:8000"
    depends_on:
      - database
  
  database:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - './mongo-data:/data/db'
